export interface PurchaseOrder {
  id: string;
  orderNo: string;
  createTime: string;
  supplierName: string;
  sku: string;
  productName: string;
  productImage: string;
  productTypesCount: number;
  totalPurchaseQty: number;
  inboundQty: number;
  unInboundQty: number;
  purchaseBoxes: number;
  inboundBoxes: number;
  actualPayAmount: number;
  extraFee: number;
  logisticsNo: string;
  logisticsStatus: string;
  shipTime: string;
  orderCreator: string;
  orderTime: string;
  payer: string;
  payTime1688: string;
  auditor: string;
  auditTime: string;
  lastOperator: string;
  lastOperateTime: string;
  buyer: string;
  orderNote: string;
  status: string;
  paymentStatus?: string;
  platformOrderNo?: string;
  ali1688AccountName?: string;
  ali1688TradeType?: string;
  platformPaymentStatus?: string;
  warehouse?: string;
  currency?: string;
  taxType?: string;
  isGift?: string;
  relatedOrderNo: string;
  signStatus?: string;
  platformStatus?: string;
  platformAmount?: number;
  customOrderNo?: string;
  trackingNo?: string;
  invoiceNo?: string;
  planNo?: string;
  receiver?: string;
  inbounder?: string;
  auditedByMe?: boolean;
  relatedPlans: {
    planNo: string;
    source: string;
    warehouse: string;
    applicant: string;
    expectShipTime: string;
    qty: number;
    note: string;
  }[];
  items?: any[];
  totalPrice?: number;
  totalQuantity?: number;
}

export const mockOrders: PurchaseOrder[] = [
  {
    id: 'PO-20260424-AUDIT-1',
    orderNo: '1570568891',
    createTime: '2026-04-24 14:00:00',
    supplierName: '审核测试供应商',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'AUDIT-001',
    productName: '待审核测试商品',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=test&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 50,
    inboundQty: 0,
    unInboundQty: 50,
    purchaseBoxes: 1,
    inboundBoxes: 0,
    actualPayAmount: 500.00,
    totalPrice: 500.00,
    totalQuantity: 50,
    extraFee: 0.00,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '测试员4',
    orderTime: '2026-04-24 13:30:00',
    payer: '--',
    payTime1688: '--',
    auditor: '--',
    auditTime: '--',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '采购员G',
    orderNote: '测试审核流转',
    status: '待审核',
    paymentStatus: '待申请付款',
    platformOrderNo: null,
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '1', sku: 'AUDIT-001', productName: '待审核测试商品', quantity: 50, price: 10, purchasePrice: 10, totalAmount: 500, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=test&image_size=square' }
    ]
  },
  {
    id: 'PO-20260409001',
    orderNo: '1570551763',
    createTime: '2026-04-09 10:30:00',
    supplierName: '东莞市柏易服饰有限公司',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'CN-BT-001',
    productName: '无线蓝牙耳机 Pro Max',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=wireless%20earbuds&image_size=square',
    productTypesCount: 2,
    totalPurchaseQty: 6497,
    inboundQty: 0,
    unInboundQty: 6497,
    purchaseBoxes: 10,
    inboundBoxes: 0,
    actualPayAmount: 49000.00,
    totalPrice: 49000.00,
    totalQuantity: 6497,
    extraFee: 150.00,
    logisticsNo: 'SF1234567890123',
    logisticsStatus: '未发货',
    shipTime: '2026-04-10 14:00:00',
    orderCreator: '张伟',
    orderTime: '2026-04-09 11:00:00',
    payer: '--',
    payTime1688: '--',
    auditor: '--',
    auditTime: '--',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '张伟',
    orderNote: '急需合并测试数据1',
    status: '新订单（未提交）',
    paymentStatus: '待申请付款',
    platformOrderNo: null,
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '1', sku: 'CN-BT-001', productName: '无线蓝牙耳机 Pro Max', quantity: 3000, price: 10, purchasePrice: 10, totalAmount: 30000, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=earbuds&image_size=square' },
      { id: '2', sku: 'CN-BT-002', productName: '无线蓝牙耳机 标准版', quantity: 3497, price: 5.43, purchasePrice: 5.43, totalAmount: 19000, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=earbuds2&image_size=square' }
    ]
  },
  {
    id: 'PO-20260409002',
    orderNo: '1570552751',
    createTime: '2026-04-09 11:30:00',
    supplierName: '东莞市柏易服饰有限公司',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'CN-BT-003',
    productName: '蓝牙音箱',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=speaker&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 2050,
    inboundQty: 0,
    unInboundQty: 2050,
    purchaseBoxes: 5,
    inboundBoxes: 0,
    actualPayAmount: 15000.00,
    totalPrice: 15000.00,
    totalQuantity: 2050,
    extraFee: 0,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '李四',
    orderTime: '2026-04-09 12:00:00',
    payer: '--',
    payTime1688: '--',
    auditor: '--',
    auditTime: '--',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '李四',
    orderNote: '急需合并测试数据2',
    status: '采购中',
    paymentStatus: '待申请付款',
    platformOrderNo: null,
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '3', sku: 'CN-BT-003', productName: '蓝牙音箱', quantity: 2050, price: 7.31, purchasePrice: 7.31, totalAmount: 15000, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=speaker&image_size=square' }
    ]
  },
  {
    id: 'PO-20260409003',
    orderNo: '1570551200',
    createTime: '2026-04-09 12:30:00',
    supplierName: '东莞市柏易服饰有限公司',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'CN-BT-004',
    productName: '智能手表',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=smartwatch&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 739,
    inboundQty: 0,
    unInboundQty: 739,
    purchaseBoxes: 2,
    inboundBoxes: 0,
    actualPayAmount: 8500.00,
    totalPrice: 8500.00,
    totalQuantity: 739,
    extraFee: 0,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '王五',
    orderTime: '2026-04-09 13:00:00',
    payer: '--',
    payTime1688: '--',
    auditor: '--',
    auditTime: '--',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '王五',
    orderNote: '急需合并测试数据3',
    status: '新订单（未提交）',
    paymentStatus: '待申请付款',
    platformOrderNo: null,
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '4', sku: 'CN-BT-004', productName: '智能手表', quantity: 739, price: 11.50, purchasePrice: 11.50, totalAmount: 8500, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=smartwatch&image_size=square' }
    ]
  },
  {
    id: 'PO-20260409004',
    orderNo: '1570550152',
    createTime: '2026-04-09 13:30:00',
    supplierName: '东莞市柏易服饰有限公司',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'CN-BT-005',
    productName: '充电宝',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=powerbank&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 744,
    inboundQty: 0,
    unInboundQty: 744,
    purchaseBoxes: 3,
    inboundBoxes: 0,
    actualPayAmount: 5200.00,
    totalPrice: 5200.00,
    totalQuantity: 744,
    extraFee: 0,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '赵六',
    orderTime: '2026-04-09 14:00:00',
    payer: '--',
    payTime1688: '--',
    auditor: '--',
    auditTime: '--',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '赵六',
    orderNote: '急需合并测试数据4',
    status: '新订单（未提交）',
    paymentStatus: '待申请付款',
    platformOrderNo: null,
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '5', sku: 'CN-BT-005', productName: '充电宝', quantity: 744, price: 6.98, purchasePrice: 6.98, totalAmount: 5200, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=powerbank&image_size=square' }
    ]
  },
  {
    id: 'PO-20260409005',
    orderNo: '1570547465',
    createTime: '2026-04-09 14:30:00',
    supplierName: '广州市贝智皮具有限公司',
    warehouse: '广州白云仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'GZ-BG-001',
    productName: '真皮手提包',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=handbag&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 200,
    inboundQty: 0,
    unInboundQty: 200,
    purchaseBoxes: 4,
    inboundBoxes: 0,
    actualPayAmount: 18000.00,
    totalPrice: 18000.00,
    totalQuantity: 200,
    extraFee: 0,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '测试员',
    orderTime: '2026-04-09 15:00:00',
    payer: '--',
    payTime1688: '--',
    auditor: '--',
    auditTime: '--',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '测试员',
    orderNote: '第二组测试1',
    status: '新订单（未提交）',
    paymentStatus: '待申请付款',
    platformOrderNo: null,
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '6', sku: 'GZ-BG-001', productName: '真皮手提包', quantity: 200, price: 90, purchasePrice: 90, totalAmount: 18000, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=handbag&image_size=square' }
    ]
  },
  {
    id: 'PO-20260409005-A',
    orderNo: '1570547466',
    createTime: '2026-04-09 14:45:00',
    supplierName: '广州市贝智皮具有限公司',
    warehouse: '广州白云仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'GZ-BG-001-A',
    productName: '真皮手提包-豪华版',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=luxury+handbag&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 50,
    inboundQty: 0,
    unInboundQty: 50,
    purchaseBoxes: 1,
    inboundBoxes: 0,
    actualPayAmount: 6000.00,
    totalPrice: 6000.00,
    totalQuantity: 50,
    extraFee: 0,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '测试员',
    orderTime: '2026-04-09 15:10:00',
    payer: '测试员',
    payTime1688: '2026-04-09 15:15:00',
    auditor: '审核员',
    auditTime: '2026-04-09 15:20:00',
    lastOperator: '测试员',
    lastOperateTime: '2026-04-09 15:25:00',
    buyer: '测试员',
    orderNote: '测试已申请付款状态',
    status: '采购中',
    paymentStatus: '已申请付款',
    platformOrderNo: '1688001002003',
    ali1688AccountName: '义翰科技',
    ali1688TradeType: '通用担保交易',
    platformPaymentStatus: '待付款',
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '6-A', sku: 'GZ-BG-001-A', productName: '真皮手提包-豪华版', quantity: 50, price: 120, purchasePrice: 120, totalAmount: 6000, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=luxury+handbag&image_size=square' }
    ]
  },
  {
    id: 'PO-20260409006',
    orderNo: '1570550185',
    createTime: '2026-04-09 15:30:00',
    supplierName: '广州市贝智皮具有限公司',
    warehouse: '广州白云仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'GZ-BG-002',
    productName: '真皮钱包',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=wallet&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 260,
    inboundQty: 0,
    unInboundQty: 260,
    purchaseBoxes: 2,
    inboundBoxes: 0,
    actualPayAmount: 5200.00,
    totalPrice: 5200.00,
    totalQuantity: 260,
    extraFee: 0,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '测试员',
    orderTime: '2026-04-09 16:00:00',
    payer: '--',
    payTime1688: '--',
    auditor: '--',
    auditTime: '--',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '测试员',
    orderNote: '第二组测试2',
    status: '新订单（未提交）',
    paymentStatus: '待申请付款',
    platformOrderNo: null,
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '7', sku: 'GZ-BG-002', productName: '真皮钱包', quantity: 260, price: 20, purchasePrice: 20, totalAmount: 5200, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=wallet&image_size=square' }
    ]
  },
  {
    id: 'PO-20260424-EXCEPTION',
    orderNo: '1570559999',
    createTime: '2026-04-24 10:00:00',
    supplierName: '异常测试供应商',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: 'EX-001',
    productName: '异常损耗商品测试',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=error%20product&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 100,
    inboundQty: 99,
    unInboundQty: 0,
    purchaseBoxes: 1,
    inboundBoxes: 1,
    actualPayAmount: 1000.00,
    totalPrice: 1000.00,
    totalQuantity: 100,
    extraFee: 0.00,
    logisticsNo: 'SF999999999',
    logisticsStatus: '已签收',
    shipTime: '2026-04-20 14:00:00',
    orderCreator: '测试员',
    orderTime: '2026-04-19 11:00:00',
    payer: '财务A',
    payTime1688: '2026-04-19 11:30:00',
    auditor: '审核员B',
    auditTime: '2026-04-19 11:15:00',
    lastOperator: '仓库员C',
    lastOperateTime: '2026-04-22 10:00:00',
    buyer: '采购员D',
    orderNote: '测试异常损耗记录',
    status: '异常',
    paymentStatus: '已完成付款',
    signStatus: '已签收',
    platformStatus: '已收货',
    platformOrderNo: '1688-9999999',
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '1', sku: 'EX-001', productName: '异常损耗商品测试', quantity: 100, inboundQty: 99, lossQty: 1, returnQty: 0, exceptionReason: '破损', price: 10, purchasePrice: 10, totalAmount: 1000, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=error%20product&image_size=square' }
    ]
  },
  {
    id: 'PO-20260424-1688MATCH',
    orderNo: '1570568888',
    createTime: '2026-04-24 11:00:00',
    supplierName: '1688对账测试供应商',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: '1688-001',
    productName: '1688对账商品',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=box&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 50,
    inboundQty: 0,
    unInboundQty: 50,
    purchaseBoxes: 1,
    inboundBoxes: 0,
    actualPayAmount: 480.00,
    totalPrice: 500.00,
    platformAmount: 450.00,
    totalQuantity: 50,
    extraFee: 0.00,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '测试员',
    orderTime: '2026-04-24 10:00:00',
    payer: '--',
    payTime1688: '--',
    auditor: '审核员B',
    auditTime: '2026-04-24 10:15:00',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '采购员D',
    orderNote: '测试1688对账差异',
    status: '1688对账',
    paymentStatus: '待申请付款',
    signStatus: '未签收',
    platformStatus: '已下单',
    platformOrderNo: '1688-8888888',
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '1', sku: '1688-001', productName: '1688对账商品', quantity: 50, price: 10, purchasePrice: 10, totalAmount: 500, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=box&image_size=square' }
    ]
  },
  {
    id: 'PO-20260424-1688MATCH-2',
    orderNo: '1570568889',
    createTime: '2026-04-24 12:00:00',
    supplierName: '1688对账测试供应商2',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: '1688-002',
    productName: '1688对账商品B',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=shoes&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 20,
    inboundQty: 0,
    unInboundQty: 20,
    purchaseBoxes: 1,
    inboundBoxes: 0,
    actualPayAmount: 180.00,
    totalPrice: 200.00,
    platformAmount: 150.00,
    totalQuantity: 20,
    extraFee: 0.00,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '测试员2',
    orderTime: '2026-04-24 11:30:00',
    payer: '--',
    payTime1688: '--',
    auditor: '审核员C',
    auditTime: '2026-04-24 11:45:00',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '采购员E',
    orderNote: '测试1688对账差异 - 第二单',
    status: '1688对账',
    paymentStatus: '待申请付款',
    signStatus: '未签收',
    platformStatus: '已下单',
    platformOrderNo: '1688-8888889',
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '1', sku: '1688-002', productName: '1688对账商品B', quantity: 20, price: 10, purchasePrice: 10, totalAmount: 200, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=shoes&image_size=square' }
    ]
  },
  {
    id: 'PO-20260424-1688MATCH-3',
    orderNo: '1570568890',
    createTime: '2026-04-24 13:00:00',
    supplierName: '1688对账测试供应商3',
    warehouse: '东莞厚街仓',
    currency: 'RMB',
    taxType: '默认',
    isGift: 'false',
    sku: '1688-003',
    productName: '1688对账商品C',
    productImage: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=hat&image_size=square',
    productTypesCount: 1,
    totalPurchaseQty: 100,
    inboundQty: 0,
    unInboundQty: 100,
    purchaseBoxes: 2,
    inboundBoxes: 0,
    actualPayAmount: 950.00,
    totalPrice: 1000.00,
    platformAmount: 900.00,
    totalQuantity: 100,
    extraFee: 0.00,
    logisticsNo: '--',
    logisticsStatus: '未发货',
    shipTime: '--',
    orderCreator: '测试员3',
    orderTime: '2026-04-24 12:30:00',
    payer: '--',
    payTime1688: '--',
    auditor: '审核员D',
    auditTime: '2026-04-24 12:45:00',
    lastOperator: '--',
    lastOperateTime: '--',
    buyer: '采购员F',
    orderNote: '测试1688对账差异 - 第三单',
    status: '1688对账',
    paymentStatus: '待申请付款',
    signStatus: '未签收',
    platformStatus: '已下单',
    platformOrderNo: '1688-8888890',
    relatedOrderNo: '--',
    relatedPlans: [],
    items: [
      { id: '1', sku: '1688-003', productName: '1688对账商品C', quantity: 100, price: 10, purchasePrice: 10, totalAmount: 1000, imageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=hat&image_size=square' }
    ]
  }
];
